/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5ddb2153c758666a71707058
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
import { Observable } from 'rxjs';

// Import Services
import { LancamentoService } from '../../services/lancamento.service';
// Import Models
import { Lancamento } from '../../domain/cc_db/lancamento';

// START - USED SERVICES
/**
* lancamentoService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* lancamentoService.list
*	@description CRUD ACTION list
*	@returns ARRAY OF lancamento
*
*/
// END - USED SERVICES

/**
 * This component shows a list of Lancamento
 * @class LancamentoListComponent
 */
@Component({
    selector: 'app-lancamento-list',
    templateUrl: './lancamento-list.component.html',
    styleUrls: ['./lancamento-list.component.css']
})
export class LancamentoListComponent implements OnInit {
    list: Observable<any[]>;
    search: any = {};
    idSelected: string;
    constructor(
        private lancamentoService: LancamentoService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.list = this.lancamentoService.list();
    }

    /**
     * Select Lancamento to remove
     *
     * @param {string} id Id of the Lancamento to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected Lancamento
     */
    deleteItem() {
        this.lancamentoService.remove(this.idSelected);
    }

}
